### ISSUE TITLE
LoadVulkanGlobalFunctions crashing all programs

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/pub.mod#13]
Hi Brucey,

Seem to have figured out my "non-Debug Print" crashes, and it was LoadVulkanGlobalFunctions from **pub.mod/vulkan.mod/vkLoader.bmx**! Turns out it crashes _any_ program, nothing to do with Print...

```
' Get the only mandatory exported function
If VulkanLibrary
    vkGetInstanceProcAddr = GetDynamicLibraryFuncAddr( VulkanLibrary,"vkGetInstanceProcAddr" )

    If vkGetInstanceProcAddr LoadVulkanGlobalFunctions()   <----- CRASHES HERE!
EndIf

Function LoadVulkanGlobalFunctions()
    vkCreateInstance = vkGetInstanceProcAddr(Null,"vkCreateInstance")
    vkEnumerateInstanceExtensionProperties = vkGetInstanceProcAddr(Null,"vkEnumerateInstanceExtensionProperties")
    vkEnumerateInstanceLayerProperties = vkGetInstanceProcAddr(Null,"vkEnumerateInstanceLayerProperties")
EndFunction

```

Why that would be, I don't know, but doing brand-new Frisky installs (using vanilla bmk) was reliably creating a build that would then crash with a simple **Print "Hello"**. Sticking an Input into Frisky between the git downloads and subsequent builds, I was able to comment out the call to LoadVulkanGlobalFunctions and then continue to get a working build.

Just did a new Frisky install as a test, didn't comment out LoadVulkanGlobalFunctions, and it's reliably crashing. (For some reason it does now open up and highlight vkLoader.bmx when it crashes, which it didn't do when I reported the error originally!)

Lest you think I am smoking ze crack:
https://www.youtube.com/watch?v=Ah6uvg_RdT8

I do appear to have vulkan-1.dll (Nvidia), BTW, but having just tried the first example I could find, [https://github.com/GameTechDev/stardust_vulkan](https://github.com/GameTechDev/stardust_vulkan) -- that opens a window and closes again, so perhaps Vulkan's not working here for whatever reason. Shouldn't be needed, obv... :P

**Comment by davecamp** [comment]
Hiya,
Most drivers are indeed still in their early stages and may exhibit occassional bad behaviour, although they are quickly getting better. I just tried the stardust demo  that you linked to on a Win7 unit with a geforce 750 with nvidia driver 368.69, and it works ok here. Here's an image of it running http://imgur.com/a/eDs9b.

To know if the vulkan drivers are properly supported you could type vulkaninfo into the command line - it should dump the gpu capabilities to the console via the vulkan interfaces or you may better off piping it to a file with say 'vulkaninfo > dump.txt'.

I know I occasssionaly have trouble with the latest nvidia driver loading on a Linux unit and it exhibits similar behaviour, but that is a different issue in that the driver doesn't load properly when booting which is solved by rebooting.

If wouldn't mind reporting back if vulkaninfo reports good support then I'll see what to do for the future... maybe make some kind of 'InitVulkan' function instead of automatically initialising.

**Comment by DruggedBunny** [comment]
Hi col, only just saw this. Didn't know about vulkaninfo, which reports OK (I think!), though does give a warning about "layers" at the top of the logfile:

[vulkaninfo.txt](https://github.com/bmx-ng/pub.mod/files/440148/vulkaninfo.txt)

**Comment by DruggedBunny** [comment]
Hi col, didn't know about vulkaninfo -- seems to report OK, as far as I can tell, other than a warning about 'layers' near the start:

[vulkaninfo.txt](https://github.com/bmx-ng/pub.mod/files/440152/vulkaninfo.txt)

**Comment by DruggedBunny** [comment]
Further to this, just downloaded a few Vulkan demos, and all appear to work with the exception of that Stardust demo! (See f***ing Sod's Law in action!)

Eg. I can build and run all bar one (raytracing.exe) of the VC++ demos at [https://github.com/SaschaWillems/Vulkan](https://github.com/SaschaWillems/Vulkan). Can also run Nvidia's fish and heli demos.

**Comment by davecamp** [comment]
I could reproduce this error when building for 32bit windows.
This is an error in the blitzmax vulkan files. I've created a pull request that fixes this error.
