### ISSUE TITLE
[Win32] Freeprocess misses option to explicitely show a console

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/pub.mod#47]
For now we can only pass `hideconsole` to a newly created process. But if you do not pass `hideconsole` this does not lead to console shown. This is because `DETACHED_PROCESS` is set there, which prohibits the creation of a console. 

https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
-> "DETACHED_PROCESS"
> For console processes, the new process does not inherit its parent's console (the default). The new process can call the AllocConsole function at a later time to create a console. For more information, see Creation of a Console.

Maybe we should also name the "default" so it is understood what is done where.

Next thing is: what we pass with `HIDECONSOLE` might not necessary be a "flag" but an "enum" (so you cannot do `HIDECONSOLE & SHOWCONSOLE & REDIRECT_OUTPUT_TO_XYZ`)

OK ... so my suggestion is simple : just add a new "flag" (SHOWCONSOLE) which explicitely creates a process with the `CREATE_NEW_CONSOLE` flag.

**Comment by GWRon** [comment]
Hmm maybe it needs something more.
The requesting user at discord reported, it opens a console ... but it does not print out stuff there.

The app itself is "closed source" (not changeable by the user) so maybe the executed process needs to do something too?

**Comment by GWRon** [comment]
Also it seems as if it is not so easy to send something from the caller to the called process (so send something to "stdin" of the called process). At least we were not able to "receive" something there via standardIOStream.ReadLine() or even getchar() ...

Send was done  via
Local p:TProcess = CreateProcess(. ..)
...
p.pipe.WriteString("test")

**Comment by braxtonrivers** [comment]
With regards to [win32] freeprocess I have noticed that something appears to be amiss with createprocess on windows as it does not always work as it should, with any subsequent calls after createprocess to process.status process.close etc all resulting in an exception, when using the stock maxide and the createprocess examples, not always but with regular use of them.

I rebuilt everything with debugging and profiling in order to try and pinpoint this further, it happens with stock maxide on windows during regular use, when it is checking for the bcc and bmk versions on startup it does not always exit gracefully to the process.close causing an exception on the splash window.
I added in a lot of extra notify's and it appears that the process is created but whenever the process information is queried is when it fails.

I have tried to compare pub.stdc  system_  on windows against the freeprocess createprocess just not too sure where it is failing, or what small detail could possibly be missing or has changed slightly on windows causing it to fail.
(I know that I could possibly restart more than I already do but once a day should be enough :-)

I will keep reading and investigating, and report back anything that may prove to be useful.
